sudo: false
language: bash
os:
  - linux
addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial
before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)
install:
  # Install ESP32 toolchain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  - sudo apt-get -y install gcc git wget make libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-cryptography python-future
  # Prepare directory for the toolchain
  - mkdir -p ~/esp
  - cd ~/esp
  # Download binary toolchain for the ESP32
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  # Make xtensa-esp32-elf available for all terminal sessions
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  # Get ESP-IDF from github
  - git clone --recursive --branch release/v3.2 https://github.com/espressif/esp-idf.git
  #- git clone --recursive https://github.com/espressif/esp-idf.git
  # Set the path to ESP-IDF directory
  - export IDF_PATH=~/esp/esp-idf
  # Install required python packages
  - python -m pip install --user -r $IDF_PATH/requirements.txt
script:
  # Go back to the git repository
  - cd $PROJECT_PATH
  # Update configuration so that kconfig doesn't start interactive mode
  - make defconfig
  # Build project from the git repository

  - |
    for file in ./test_scripts/* 
      do
        cp "$file" "./main/main.cpp"
        echo Compiling $file -------------------------------------------------
        make -j4
      done
